version: '3.9'
services:
  eureka-server:
    image: eureka-server:1.0
    build:
      context: ./services/eureka-server
    ports:
      - "8761:8761"
  api-gateway:
    image: api-gateway:1.0
    build:
      context: ./services/api-gateway
    ports:
      - "8005:8005"
    depends_on:
      - eureka-server
  product-service:
    image: product-service:1.0
    build:
      context: ./services/product-service
    ports:
      - "8001:8001"
    depends_on:
      - eureka-server
  product-service-2:
    image: product-service:1.0
    build:
      context: ./services/product-service
    ports:
      - "8003:8003"
    depends_on:
      - eureka-server
  order-service:
    image: order-service:1.0
    build:
      context: ./services/order-service
    ports:
      - "8002:8002"
    depends_on:
      - eureka-server