name: Build and Deploy Microservices

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push order-service Docker image
        run: |
          cd order-service
          docker build -t your-docker-username/order-service:1.0 .
          docker push your-docker-username/order-service:1.0

      - name: Build and push api-gateway Docker image
        run: |
          cd api-gateway
          docker build -t jumongweb/api-gateway:1.0 .
          docker push jumongweb/api-gateway:1.0

      - name: Build and push product-service Docker image
        run: |
          cd product-service
          docker build -t jumongweb/product-service:1.0 .
          docker push jumongweb/product-service:1.0